apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: "1Gi"
    requests.ephemeral-storage: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    limits.ephemeral-storage: "8Gi"
